# Generated by Django 4.2 on 2023-04-27 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BankModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_banks', models.CharField(max_length=20)),
                ('mortgage_rate', models.FloatField(default=0.0)),
                ('payment', models.IntegerField(default=0)),
            ],
        ),
    ]
