# Generated by Django 4.2 on 2023-05-18 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banks', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bankmodel',
            old_name='payment',
            new_name='payment_max',
        ),
        migrations.RenameField(
            model_name='bankmodel',
            old_name='mortgage_rate',
            new_name='rate_max',
        ),
        migrations.AddField(
            model_name='bankmodel',
            name='payment_min',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='bankmodel',
            name='rate_min',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='bankmodel',
            name='term_max',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='bankmodel',
            name='term_min',
            field=models.IntegerField(default=0),
        ),
    ]
